### ISSUE TITLE
well known IP range data sources

### ISSUE THREAD

**Issue by wasaga** [pomerium/datasource#24]
**Is your feature request related to a problem? Please describe.**

Webhooks is a popular way of communicating between systems, and many providers publish their known IP blocks ranges. i.e.

- [GitHub](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses)
- [Azure cloud](https://www.microsoft.com/en-us/download/details.aspx?id=56519)
- [BitBucket / Confluence / other Atlassian products](https://ip-ranges.atlassian.com/)
- Query per autonomous system belonging to the organization - i.e. `whois -h whois.radb.net -- '-i origin AS32934' | grep ^route`  for Facebook webhooks
- [Apple domain validation](https://developer.apple.com/documentation/apple_pay_on_the_web/setting_up_your_server#3179116)
- [AWS](https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html)
- [Stripe webhooks](https://stripe.com/files/ips/ips_webhooks.json)
- [PagerDuty webhooks](https://developer.pagerduty.com/docs/9a349b09b87b7-webhook-i-ps)

**Describe the solution you'd like**

mostly coming in JSON, but formats seem to differ a lot. 
- Maybe a general purpose JSON transformation plugin - i.e. using https://github.com/itchyny/gojq along with transformation recepies for known providers, that ensures the output format is correct. 
- or just docs with few examples?

**Describe alternatives you've considered**

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by alexfornuto** [comment]
Re-opening since the scope of what we will document has changed.

You can use the template and add additional pages to the branch for this PR: https://github.com/pomerium/documentation/pull/73
