### ISSUE TITLE
Azure IP range URL is not stable

### ISSUE THREAD

**Issue by wasaga** [pomerium/datasource#42]
## What happened?

Azure IP range URL is gone 

https://github.com/pomerium/datasource/blob/323f3748c8e25c33b6c17d1a190a324075c45e17/internal/wellknownips/azure.go#L22

current is https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220718.json 

apparently it changes periodically and is not static.

**Comment by wasaga** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=56519 this page URL is stable, but it requires you to click the button to download an actual file.

**Comment by desimone** [comment]
Let's gZIP and Embed.
