### ISSUE TITLE
Help output reports wrong binary name.

### ISSUE THREAD

**Issue by alexfornuto** [pomerium/datasource#46]
## What happened?

The compiled binary is named `datasource`. The help output assumes a binary named `pomerium-datasource`:

```
Run 'pomerium-datasource --help' for usage.
```

## What did you expect to happen?

The help output and file name to match.

**Comment by desimone** [comment]
This should be fixed with :

- https://github.com/pomerium/datasource/pull/50
- https://github.com/pomerium/datasource/pull/51

Can you confirm @alexfornuto ?

**Comment by alexfornuto** [comment]
Confirmed!
